services:
  postgres:
    image: postgres:17
    container_name: postgres17-container
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: R00t_P@ssw0rd_2026!Secure
      POSTGRES_DB: railway
      POSTGRES_USER: administrador_user
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: